name: Build and Push Docker Image

on:
  push:
    branches:
      - Objetivo5
    paths:
      - 'Dockerfile'
      - '**.go'
      - 'go.mod'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: abbonno/healthscheduler:latest

  test:
    runs-on: ubuntu-latest
    needs: build  # Se ejecuta después de construir la imagen
    steps:
      - name: Run container and test
        run: docker run -t -v `pwd`:/app/test abbonno/healthscheduler
